
FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.8

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com \
    && apt-get update --allow-insecure-repositories \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces

# Install Python dependencies from requirements
COPY requirements.txt requirements_test.txt requirements_dev.txt ./
RUN pip3 install -r requirements_test.txt -r requirements_dev.txt -r requirements.txt

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
